Generate meals inputData class and InputBoundary class finished.
merrickliu888/NutriNinja pull request #11
Opened 2023-11-08 17:01 UTC by jackkfan0305

@merrickliu888 lmk if there are any questions.

2023-11-08 17:38 UTC, merrickliu888 requested changes
@samaslanowicz made a good point. We should change ```health``` to ```healthPreferences```. Oh and for consistency, we should decide one ```protein``` or ```prot``` as the identifier for protein. I can change mine, its up to you, I do not have a preference.
Otherwise, perfect!

2023-11-08 18:30 UTC, jackkfan0305 commented
Yes, good point. I've made such changes. For consistency,  let's use   ```protein``` as the identifier.

2023-11-12 15:05 UTC, jackkfan0305 commented
I finished the use cases for generate meals @vrindasubhash @merrickliu888 @stefanateljevic04 @samaslanowicz review and lmk if there are problems

2023-11-13 18:41 UTC, merrickliu888 requested changes
Delete the DataAccessInterface. See comment.

2023-11-13 18:41 UTC, merrickliu888 commented on src/use_case/generate_meal/GenerateMealDataAccessInterface.java
This file is unmercenary because this use case is not saving anything. We will use the `savePreferences` use case to save the preferences.

2023-11-13 18:48 UTC, merrickliu888 commented on src/use_case/generate_meal/GenerateMealOutputData.java
Also, what are `Hits`. Either add clarifying comments or rename it to something else, like calling it `Meals`.

2023-11-13 19:37 UTC, merrickliu888 approved these changes
Looks good!

2023-11-13 19:37 UTC, merged

2023-12-05 21:25 UTC, samaslanowicz reviewed
just put some places to add javadocs

2023-12-05 21:25 UTC, samaslanowicz commented on src/use_case/generate_meal/GenerateMealUseCaseInteractor.java
> +    public void execute(GenerateMealInputData inputData) {
add a javadoc to this method

2023-12-05 21:25 UTC, samaslanowicz commented on src/interface_adapter/generate_meal/GenerateMealController.java
> +    public void execute(List<String> healthPreferences, List<String> mealType, List<String> dishType, int calMin, int calMax, int carbMin, int carbMax, int proteinMin, int proteinMax, int fatMin, int
add a javadoc to this method