Added/customized all of the signup usecase files from the CA homework.
merrickliu888/NutriNinja pull request #13
Opened 2023-11-09 21:48 UTC by stefanateljevic04

All of the necessary files / clean architecture components of the signup use case. I'll wait for Vrinda's pull request to be approved before adding changes to main. @vrindasubhash @jackkfan0305 can you review this?

2023-11-10 02:27 UTC, vrindasubhash reviewed
Coding styles looks good, except for naming conventions for the use_case directory there seems to be an underscore "use_case_signup", I believe it should look like "use_case/signup", I think you can fix this by making signup a folder in the use_case folder. There does not seem to be any errors, but we can test it when we have enough code such that it compiles. Adheres to CA and SOLID. Looks good stef!

2023-11-10 02:39 UTC, jackkfan0305 commented
Adding onto what @vrindasubhash said, you should create packages under our pre-existing packages. For example, under ```interface_adapter```, you should create another package called ```signup``` and put everything related to interface_adapter and so on. This keeps everything orgainzed and prevents merging issues. Other than that, everything looks good!

2023-11-13 19:18 UTC, merrickliu888 requested changes
Overall good start. Here are some suggestions:
- Separate the view, viewmodel, state, presenter classes into another PR. 
- Remove all the comments on the top of the file mentioning the decompiler.
- Make sure your calls to the FileDataAccessObject have the right method names.
- Make the variable naming scheme more informative and consistent.
- Remove anything with saving the time the user was created. We are not using it.

2023-11-13 19:18 UTC, merrickliu888 commented on src/interface_adapter/signup/SignupController.java
> +//
What is this? Could we remove it?

2023-11-13 19:18 UTC, merrickliu888 commented on src/use_case_signup/SignupInputBoundary.java
> +    void execute(SignupInputData var1);
For readability purposes, could you change this to a more informative name, like `signupInputData`.

2023-11-13 19:18 UTC, merrickliu888 commented on src/use_case_signup/SignupInputData.java
> +    private final String repeatPassword;
Keep the variable names consistent. Above you call it `password1` and `password2`. I think `repeatPassword` is more informative, so if you could change the name of the password variables to be consistent, that would make readability better.

2023-11-13 19:18 UTC, merrickliu888 commented on src/use_case_signup/SignupInteractor.java
> +        if (this.userDataAccessObject.existsByName(signupInputData.getUsername())) {
Change the methods calls here to the FileDataAccessObject to be consistent with the ones in the FileDataAccessObject.

2023-11-13 19:18 UTC, merrickliu888 commented on src/use_case_signup/SignupOutputData.java
> +    public void setCreationTime(String creationTime) {
We don't need anything regarding creationTime so remove it.

2023-11-13 19:18 UTC, merrickliu888 commented on src/use_case_signup/SignupUserDataAccessInterface.java
> +    boolean existsByName(String var1);
Use more informative variable names.

2023-11-14 19:27 UTC, merrickliu888 requested changes
File DAO changes to match function signatures of current implementation.

2023-11-14 19:27 UTC, merrickliu888 commented on src/use_case_signup/SignupUserDataAccessInterface.java
> +    boolean existsByName(String var1);
Change this function signature to `boolean userExists(String username)`

2023-11-15 00:05 UTC, samaslanowicz commented on src/interface_adapter/signup/SignupPresenter.java
> +        response.setCreationTime(responseTime.format(DateTimeFormatter.ofPattern("hh:mm:ss")));
I don't think we need to show creation time or response time, you could probably remove these two lines

2023-11-15 00:06 UTC, samaslanowicz commented on src/use_case_signup/SignupInteractor.java
> +            LocalDateTime now = LocalDateTime.now();
Here too, could probably just remove the creationTime variable from the SignUpOutputData Class

2023-11-15 00:08 UTC, samaslanowicz commented
I also just added a few comments on the files, but seems like Merrick already covered most of it. Other than that, looks good to me! Probably ready to merge in once you make some of those small edits.

2023-11-16 04:14 UTC, stefanateljevic04 commented
@merrickliu888 @samaslanowicz I made the changes and committed, thanks for the feedback

2023-11-17 01:04 UTC, merrickliu888 approved these changes
Looks good.

2023-11-17 01:04 UTC, merged

2023-12-07 23:55 UTC, samaslanowicz commented on src/interface_adapter/signup/SignupController.java
> +    public void execute(String username, String password, String repeatPassword) {
should add a javadoc for this method

2023-12-07 23:56 UTC, samaslanowicz commented on src/use_case_signup/SignupInteractor.java
> +    public void execute(SignupInputData signupInputData) {
javadoc here too. should be added to any public methods