First version of SavePreferences use case
merrickliu888/NutriNinja pull request #15
Opened 2023-11-11 20:34 UTC by samaslanowicz

Completed all of the classes in the save preferences use case, as well as the controller. I also attemped a first draft of the presenter, view model, and state classes, but I am still a little unsure of what methods I need to add and what variables need to be initialized. Since the view does not change when the save preferences button is pressed, do I still need the firePropertyChange methods? What else do I need to put in my presenter and view model? Can you guys check this out @vrindasubhash @merrickliu888 @jackkfan0305 @stefanateljevic04

2023-11-12 14:53 UTC, jackkfan0305 reviewed
I think you should change the ```void savePreferences()``` method name in SaveDataAccessInterface to ```void save()```. Since FileDataAccessObject will implement the interface, ```save()``` method will already save user preferences so making another  ```savePreferences()``` method is redundant. Otherwise, everything else looks good!

2023-11-13 19:21 UTC, merrickliu888 requested changes
Nice. Just separate the frontend classes to another PR. Also, refactor some of the variables like Jack said in Lab.

2023-11-14 19:24 UTC, merrickliu888 requested changes

2023-11-14 19:24 UTC, merrickliu888 commented on src/use_case/save_preferences/SavePreferencesDataAccessInterface.java
> +    void savePreferences();
Change the function signature to `void saveUserPreference(String username, UserPreference preference)`

2023-11-17 00:46 UTC, merrickliu888 approved these changes
Looks good. Now we just have to test, and if anything comes up we'll fix it. We'll also need to re-evaluate some of the front end things, but that is for another PR.

2023-11-17 00:46 UTC, merged