Added junit tests for login usecase interactor.
merrickliu888/NutriNinja pull request #23
Opened 2023-11-19 07:01 UTC by vrindasubhash

Added a few test cases and confirmed the login usecase interactor works as expected.

Tests:
1) Existing user logins in with correct password
2) Non-existent user tries to login
3) Wrong password for existing user

2023-11-19 07:38 UTC, merrickliu888 commented
@vrindasubhash could you attach a screen shot of your coverage with the tests? Thanks!

2023-11-19 07:42 UTC, vrindasubhash commented
<img width="531" alt="Screenshot 2023-11-19 at 2 41 17 AM" src="https://github.com/merrickliu888/NutriNinja/assets/30160343/abda2e25-2457-45bb-9261-4fcdeeb2e890">

2023-11-20 18:17 UTC, merrickliu888 requested changes
Overall looks good. Pretty much got everything, just some small changes.

2023-11-20 18:17 UTC, merrickliu888 commented on test/use_case/login/LoginInteractorTest.java
> +        this.userDataAccessObject.saveUser(new CommonUser(this.firstUser, this.firstPassword, null));
Don't use the `CommonUser` constructor, use the `UserFactory` which can also create a default user with default preferences.

2023-11-20 18:17 UTC, merrickliu888 commented on test/use_case/login/LoginInteractorTest.java
> +    public void testUserExistsAndPasswordCorrect() {
Test the `userPreferences` values too.

2023-11-20 18:17 UTC, merrickliu888 commented on test/use_case/login/LoginInteractorTest.java
> +    public void tearDown() throws Exception {
Not necessary in this case.

2023-11-20 18:17 UTC, merrickliu888 commented on test/use_case/login/LoginInteractorTest.java
> +        this.userDataAccessObject = new MemoryUserDataAccessObject();
You can instantiate this above when you first declare this `userDataAccessObject`, so you don't have to reinstantiate it each time.

2023-11-20 19:02 UTC, merrickliu888 approved these changes
Good changes. Thanks for removing the import.

2023-11-20 19:02 UTC, merged

2023-11-20 19:03 UTC, vrindasubhash commented
<img width="816" alt="Screenshot 2023-11-20 at 2 03 16 PM" src="https://github.com/merrickliu888/NutriNinja/assets/30160343/ecc30f48-26b0-4604-b941-4910726519e8">

Coverage now 100%