Random meal generation controller, and use cases except interactor finished
merrickliu888/NutriNinja pull request #34
Opened 2023-11-21 19:42 UTC by jackkfan0305

@vrindasubhash @merrickliu888 @stefanateljevic04 @samaslanowicz Review and lmk if there are any problems

2023-11-21 20:49 UTC, merrickliu888 requested changes
Also could what changes did you make to your GenerateMealOutputData?

2023-11-21 20:49 UTC, merrickliu888 commented on src/use_case/generate_meal_by_id/GenerateMealByIDOutputData.java
> +import use_case.generate_meal.GenerateMealOutputData;
Watch out for this. When you copy and paste from other classes Intellij refactors and assume you want the class there. Also why is `GenerateMealOutputData` here?

2023-11-21 20:49 UTC, merrickliu888 commented on src/use_case/generate_meal_by_id/GenerateMealByIDOutputData.java
> +            private TotalNutrients.Nutrients PROCNT; //protein
Why is it `TotalNutrients.Nutrients` instead of just `Nutrients`?

2023-11-21 20:49 UTC, merrickliu888 commented on src/interface_adapter/generate_random_meal/GenerateRandomMealController.java
> +    public void execute(String mealID){
`execute()` should not have any parameters.  Generate the random `mealID` in the controller using `Random` and selecting a random index in the class that holds the `mealIDs`. I only say this not to clutter the view.

2023-11-23 21:44 UTC, jackkfan0305 commented
> Also could what changes did you make to your GenerateMealOutputData?

Changed public to private methods.

2023-11-23 21:45 UTC, jackkfan0305 commented
@merrickliu888 I fixed the errors you pointed out. Lmk if there are any more

2023-11-24 01:03 UTC, merrickliu888 approved these changes
Looks good, and good use of static. In the future, if we need to change the instance attribute of RecipesList to private, we can just make a static getter method.

2023-11-24 01:04 UTC, merged