View/Viewmodel/Presenter/State for signup use case
merrickliu888/NutriNinja pull request #45
Opened 2023-11-25 19:32 UTC by stefanateljevic04

Implemented all of the required components of the view for the signup use case. Created a main method in the signupview class to test that the view works, shown in screenshot:

<img width="1389" alt="Screen Shot 2023-11-25 at 2 23 08 PM" src="https://github.com/merrickliu888/NutriNinja/assets/128317724/91f2cb0c-9b55-4221-a902-11cbbf96240c">

@vrindasubhash @merrickliu888 @jackkfan0305 @samaslanowicz can you guys review this?

2023-11-25 23:37 UTC, merrickliu888 commented
@stefanateljevic04 Looks solid. But what is the purpose of clear? And could you change the name of the text boxes to what they would look like on say a gmail sign up ie. instead of "Choose username" just do Username. Also get rid of the Sign Up View header. But def looking good!

2023-11-26 07:28 UTC, stefanateljevic04 commented
@merrickliu888 I made the changes, here's the new screenshot:

<img width="422" alt="Screen Shot 2023-11-26 at 2 25 28 AM" src="https://github.com/merrickliu888/NutriNinja/assets/128317724/b4afdf0d-2639-4e4f-9a36-55e9ce99045d">

2023-11-26 07:32 UTC, stefanateljevic04 commented
@merrickliu888 should I get rid of cancel also?

2023-11-27 03:07 UTC, merrickliu888 commented
> @merrickliu888 should I get rid of cancel also?

Does it have any functionality. It would also be useful to have a button like "already have an account? Sign in"

2023-11-27 04:01 UTC, stefanateljevic04 commented
> > @merrickliu888 should I get rid of cancel also?
> 
> Does it have any functionality. It would also be useful to have a button like "already have an account? Sign in" Unless thats what cancel is for. We do not want users being stuck on the signup page.

That makes sense, I'l turn cancel into that

2023-11-27 07:03 UTC, stefanateljevic04 commented
> > @merrickliu888 should I get rid of cancel also?
> 
> Does it have any functionality. It would also be useful to have a button like "already have an account? Sign in" Unless thats what cancel is for. We do not want users being stuck on the signup page.

Ok I made the changes, here's what it looks like now 

<img width="397" alt="Screen Shot 2023-11-27 at 2 01 05 AM" src="https://github.com/merrickliu888/NutriNinja/assets/128317724/4472ad4f-8e43-4a14-a063-723155d6c8e5">

2023-11-27 18:23 UTC, merrickliu888 requested changes
Awesome! Just need to change some variable names!

2023-11-27 18:23 UTC, merrickliu888 commented on src/view/SignupView.java
> +                String var10001 = SignupView.this.repeatPasswordInputField.getText();
What is `var10001`?

2023-11-27 18:23 UTC, merrickliu888 commented on src/view/SignupView.java
> +                String var10000 = SignupView.this.usernameInputField.getText();
What is `var10000`?

2023-11-27 18:33 UTC, merrickliu888 approved these changes
Solid. Now we just need to do some integration tests.

2023-11-27 18:33 UTC, merged